//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public double AddressLat { get; set; }
        public double AddressLong { get; set; }
        public string AddressDescription { get; set; }
        public string StudentID { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
