//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Subscriptions = new HashSet<Subscription>();
            this.TripCategories = new HashSet<TripCategory>();
        }
    
        public int ScheduleID { get; set; }
        public string ScheduleME { get; set; }
        public string ScheduleDay { get; set; }
        public string ScheduleDescription { get; set; }
    
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<TripCategory> TripCategories { get; set; }
    }
}
