//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledTrip
    {
        public ScheduledTrip()
        {
            this.DailyTrips = new HashSet<DailyTrip>();
            this.StudentScheduledTrips = new HashSet<StudentScheduledTrip>();
        }
    
        public int ScheduledTripID { get; set; }
        public int BusID { get; set; }
        public string DriverID { get; set; }
        public int TripCategoryID { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual ICollection<DailyTrip> DailyTrips { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual TripCategory TripCategory { get; set; }
        public virtual ICollection<StudentScheduledTrip> StudentScheduledTrips { get; set; }
    }
}
