//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public double SchoolLat { get; set; }
        public double SchoolLong { get; set; }
        public string SchoolPhoto { get; set; }
        public string SchoolLogo { get; set; }
        public string SchoolPhoneNumber { get; set; }
        public string SchoolAddress { get; set; }
    }
}
