//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentScheduledTrip
    {
        public int ScheduledTripID { get; set; }
        public string StudentID { get; set; }
        public int StudentScheduledTripOrder { get; set; }
    
        public virtual ScheduledTrip ScheduledTrip { get; set; }
        public virtual Student Student { get; set; }
    }
}
