//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Addresses = new HashSet<Address>();
            this.StudentDailyTrips = new HashSet<StudentDailyTrip>();
            this.StudentScheduledTrips = new HashSet<StudentScheduledTrip>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Parents = new HashSet<Parent>();
        }
    
        public string StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentGender { get; set; }
        public Nullable<System.DateTime> StudentBirthdate { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentThumbPhoto { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Class Class { get; set; }
        public virtual ICollection<StudentDailyTrip> StudentDailyTrips { get; set; }
        public virtual ICollection<StudentScheduledTrip> StudentScheduledTrips { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
    }
}
