//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDailyTrip
    {
        public int DailyTripID { get; set; }
        public string StudentID { get; set; }
        public string StudentDailyTripStatus { get; set; }
        public Nullable<System.TimeSpan> StudentDailyTripCheckTime { get; set; }
        public Nullable<int> StudentDailyTripOrder { get; set; }
        public Nullable<double> StudentDailyTripLat { get; set; }
        public Nullable<double> StudentDailyTripLong { get; set; }
    
        public virtual DailyTrip DailyTrip { get; set; }
        public virtual Student Student { get; set; }
    }
}
