//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public string StudentID { get; set; }
        public int ScheduleID { get; set; }
        public string SubscriptionYN { get; set; }
        public int AddressID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
