//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUser
    {
        public string SUserID { get; set; }
        public string SUserPassword { get; set; }
        public string SUserFirstName { get; set; }
        public string SUserLastName { get; set; }
        public string SUserRole { get; set; }
        public string SUserPhoto { get; set; }
        public string SUserThumbPhoto { get; set; }
    }
}
