//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripCategory
    {
        public TripCategory()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int TripCategoryID { get; set; }
        public int ScheduleID { get; set; }
        public System.TimeSpan TripCategoryTime { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual ScheduledTrip ScheduledTrip { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
