//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentBusSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAppMenu
    {
        public int WebAppMenuID { get; set; }
        public string WebAppMenuText { get; set; }
        public string WebAppMenuURL { get; set; }
        public Nullable<int> WebAppMenuParent { get; set; }
        public Nullable<int> WebAppMenuPosition { get; set; }
        public string WebAppMenuRole { get; set; }
    }
}
